### ISSUE TITLE
125 먼저 하는 팀 리애쏘기

### ISSUE THREAD

**Issue by 42hm** [42-cub3d/cub3d#7]
Call?

**Comment by enaenen** [comment]
먼저 하신분들이 기분좋아서 쏘셔야하는것 아닐까요..?ㅋㅋㅋㅋ

**Comment by codeyoma** [comment]
아~ 저희는 아쉽게도 100이 맥스랍니다! 우하하하!

**Comment by 42hm** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ허허허.............허허....허허?? 100이 맥스입니까??

**Comment by 42hm** [comment]
벽충돌만 해서 105 합시다..!

**Comment by 42hm** [comment]
와 이팀은 마일스톤까지..? 7일컷..?

**Comment by codeyoma** [comment]
ㅋㅋㅋ 맨다토리 7일컷 도전 !!!!!

**Comment by 42hm** [comment]
자자 템플렛도 만들자구.... 이슈 템플렛!
